version: "2"
services:
  jenkins:
    image: acefei/ace-jenkins-master
    container_name: jenkins
    ports:
    - "80:8080"
    - "50000:50000"
    environment:
    - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    volumes:
    - jenkins-master:/var/jenkins_home

  worker:
    image: acefei/ace-jenkins-worker
    depends_on:
        - jenkins
    environment:
      JENKINS_SLAVE_SSH_PUBKEY: ${JENKINS_SLAVE_SSH_PUBKEY}
    volumes:
    - jenkins-worker:/home/jenkins

volumes:
  jenkins-master:
  jenkins-worker:
