version: '2'
services:
  jenkins:
    image: acefei/jenkins-lts
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    volumes:
      - 'jenkins_data:/var/jenkins_home'

volumes:
  jenkins_data:
